version: '3'

services: 
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog_hostel
    command: --default-authentication-plugin=mysql_native_password
    #command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      #- ./sql:/var/lib/mysql/
      #- ./mydb.sql:/docker-entrypoint-initdb.d/mydb.sql
      - ./sql:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default
  www:
    build: .
    container_name: www
    restart: always
    links:
      - db
    ports:
      - 8080:80
    volumes: 
      - ./www/:/var/www/html/
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - db:db
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      #PMA_USER: user
      #PMA_PASSWORD: 1234
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - default
volumes:
    persistent:
